-- Drop de as tablas--
DROP TABLE administrador CASCADE CONSTRAINTS;

DROP TABLE agencia_externa CASCADE CONSTRAINTS;

DROP TABLE articulo CASCADE CONSTRAINTS;

DROP TABLE checkin CASCADE CONSTRAINTS;

DROP TABLE checkout CASCADE CONSTRAINTS;

DROP TABLE cliente CASCADE CONSTRAINTS;

DROP TABLE comuna CASCADE CONSTRAINTS;

DROP TABLE condominio CASCADE CONSTRAINTS;

DROP TABLE conductor CASCADE CONSTRAINTS;

DROP TABLE cont_serv CASCADE CONSTRAINTS;

DROP TABLE departamento CASCADE CONSTRAINTS;

DROP TABLE disponibilidad CASCADE CONSTRAINTS;

DROP TABLE funcionario  CASCADE CONSTRAINTS;

DROP TABLE gastos CASCADE CONSTRAINTS;

DROP TABLE mantencion CASCADE CONSTRAINTS;

DROP TABLE marca CASCADE CONSTRAINTS;

DROP TABLE modelo CASCADE CONSTRAINTS;

DROP TABLE region CASCADE CONSTRAINTS;

DROP TABLE res_mant CASCADE CONSTRAINTS;

DROP TABLE reserva CASCADE CONSTRAINTS;

DROP TABLE servextras CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

DROP TABLE transporte CASCADE CONSTRAINTS;

DROP TABLE usuario CASCADE CONSTRAINTS;

DROP TABLE vehiculo CASCADE CONSTRAINTS;
