//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICULO
    {
        public int ID_ARTI { get; set; }
        public string NOM_ARTI { get; set; }
        public Nullable<short> CANT_ARTI { get; set; }
        public string DETA_ARTI { get; set; }
        public int VALOR_ARTI { get; set; }
        public int ID_DPTO { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
    }
}
