//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKIN
    {
        public int ID_RVA { get; set; }
        public string DETA_CHI { get; set; }
        public int ID_USR { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
