//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.AGENCIA_EXTERNA = new HashSet<AGENCIA_EXTERNA>();
            this.CONDOMINIO = new HashSet<CONDOMINIO>();
        }
    
        public short ID_COM { get; set; }
        public string NOM_COM { get; set; }
        public short ID_RGN { get; set; }
    
        public virtual ICollection<AGENCIA_EXTERNA> AGENCIA_EXTERNA { get; set; }
        public virtual REGION REGION { get; set; }
        public virtual ICollection<CONDOMINIO> CONDOMINIO { get; set; }
    }
}
