//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDOMINIO
    {
        public CONDOMINIO()
        {
            this.DEPARTAMENTO = new HashSet<DEPARTAMENTO>();
        }
    
        public short ID_CND { get; set; }
        public string NOM_CND { get; set; }
        public short ID_COM { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<DEPARTAMENTO> DEPARTAMENTO { get; set; }
    }
}
