//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONT_SERV
    {
        public int ID_CONT_SERV { get; set; }
        public System.DateTime FEC_CONT { get; set; }
        public int COSTO_TOTAL { get; set; }
        public string DETA_CONT { get; set; }
        public System.DateTime FEC_ACORD { get; set; }
        public string HORA_ACORD { get; set; }
        public string LUGAR_RECOGIDA { get; set; }
        public string LUGAR_DESTINO { get; set; }
        public Nullable<decimal> KM_REC { get; set; }
        public string EST_CONT { get; set; }
        public int ID_RVA { get; set; }
        public int ID_SERV { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual SERVEXTRAS SERVEXTRAS { get; set; }
    }
}
