//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPONIBILIDAD
    {
        public System.DateTime FEC_DISP { get; set; }
        public string ESTA_DISP { get; set; }
        public int ID_DPTO { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
    }
}
