//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELO
    {
        public MODELO()
        {
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public short ID_MODELO { get; set; }
        public string NOMBRE_MODELO { get; set; }
        public short ID_MARCA { get; set; }
    
        public virtual MARCA MARCA { get; set; }
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
