//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int ID_RVA { get; set; }
        public int MONTO_TOTAL { get; set; }
        public int MONTO_ARR { get; set; }
        public int ABONO_REQ { get; set; }
        public int MONTO_SERV_EXTRA { get; set; }
        public int MONTO_MULTAS { get; set; }
        public int MONTO_PAGADO { get; set; }
        public string EST_PAGO { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
    }
}
