//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RES_MANT
    {
        public RES_MANT()
        {
            this.MANTENCION = new HashSet<MANTENCION>();
        }
    
        public int ID_RMANT { get; set; }
        public System.DateTime FEC_RMANT { get; set; }
        public int ID_DPTO { get; set; }
        public int ID_USR { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual ICollection<MANTENCION> MANTENCION { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
