//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.CONT_SERV = new HashSet<CONT_SERV>();
        }
    
        public int ID_RVA { get; set; }
        public System.DateTime FEC_INI_RVA { get; set; }
        public System.DateTime FEC_FIN_RVA { get; set; }
        public short NUM_PERS { get; set; }
        public string ESTADO_RVA { get; set; }
        public int ID_DPTO { get; set; }
        public int ID_USR { get; set; }
    
        public virtual CHECKIN CHECKIN { get; set; }
        public virtual CHECKOUT CHECKOUT { get; set; }
        public virtual ICollection<CONT_SERV> CONT_SERV { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual PAGO PAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
