//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVEXTRAS
    {
        public SERVEXTRAS()
        {
            this.CONT_SERV = new HashSet<CONT_SERV>();
        }
    
        public int ID_SERV { get; set; }
        public string NOM_SERV { get; set; }
        public string TIPO_SERV { get; set; }
        public string DESC_SERV { get; set; }
        public int ID_AGENCIA { get; set; }
    
        public virtual AGENCIA_EXTERNA AGENCIA_EXTERNA { get; set; }
        public virtual ICollection<CONT_SERV> CONT_SERV { get; set; }
        public virtual TOUR TOUR { get; set; }
        public virtual TRANSPORTE TRANSPORTE { get; set; }
    }
}
