//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        public int ID_SERV { get; set; }
        public short DUR_HRA { get; set; }
        public short DUR_MIN { get; set; }
        public int COST_ADULT { get; set; }
        public int COST_NIGNO { get; set; }
        public int COST_3RA { get; set; }
        public string UBI_PARTIDA { get; set; }
        public string UBI_FIN { get; set; }
        public string ALIMENTACION { get; set; }
        public string TRANSPORTE { get; set; }
    
        public virtual SERVEXTRAS SERVEXTRAS { get; set; }
    }
}
