//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public TRANSPORTE()
        {
            this.CONDUCTOR = new HashSet<CONDUCTOR>();
        }
    
        public int ID_SERV { get; set; }
        public short COST_KM_DIA { get; set; }
        public short COST_KM_NOC { get; set; }
    
        public virtual ICollection<CONDUCTOR> CONDUCTOR { get; set; }
        public virtual SERVEXTRAS SERVEXTRAS { get; set; }
    }
}
