//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TurismoRealEntities : DbContext
    {
        public TurismoRealEntities()
            : base("name=TurismoRealEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGENCIA_EXTERNA> AGENCIA_EXTERNA { get; set; }
        public DbSet<ARTICULO> ARTICULO { get; set; }
        public DbSet<CHECKIN> CHECKIN { get; set; }
        public DbSet<CHECKOUT> CHECKOUT { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<CONDOMINIO> CONDOMINIO { get; set; }
        public DbSet<CONDUCTOR> CONDUCTOR { get; set; }
        public DbSet<CONT_SERV> CONT_SERV { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<DISPONIBILIDAD> DISPONIBILIDAD { get; set; }
        public DbSet<GASTOS> GASTOS { get; set; }
        public DbSet<MANTENCION> MANTENCION { get; set; }
        public DbSet<MARCA> MARCA { get; set; }
        public DbSet<MODELO> MODELO { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<REGION> REGION { get; set; }
        public DbSet<RES_MANT> RES_MANT { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<SERVEXTRAS> SERVEXTRAS { get; set; }
        public DbSet<TIPO_USUARIO> TIPO_USUARIO { get; set; }
        public DbSet<TOUR> TOUR { get; set; }
        public DbSet<TRANSPORTE> TRANSPORTE { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VEHICULO> VEHICULO { get; set; }
    
        public virtual int PD_INSERT_FECHAS(Nullable<decimal> v_ID_DEPTO)
        {
            var v_ID_DEPTOParameter = v_ID_DEPTO.HasValue ?
                new ObjectParameter("V_ID_DEPTO", v_ID_DEPTO) :
                new ObjectParameter("V_ID_DEPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PD_INSERT_FECHAS", v_ID_DEPTOParameter);
        }
    
        public virtual int SP_AGREGARAGENCIAEXTERNA(string v_NOM_AGE, string v_EMAIL_AGE, Nullable<decimal> v_TEL_AGE, Nullable<decimal> v_ID_COM)
        {
            var v_NOM_AGEParameter = v_NOM_AGE != null ?
                new ObjectParameter("V_NOM_AGE", v_NOM_AGE) :
                new ObjectParameter("V_NOM_AGE", typeof(string));
    
            var v_EMAIL_AGEParameter = v_EMAIL_AGE != null ?
                new ObjectParameter("V_EMAIL_AGE", v_EMAIL_AGE) :
                new ObjectParameter("V_EMAIL_AGE", typeof(string));
    
            var v_TEL_AGEParameter = v_TEL_AGE.HasValue ?
                new ObjectParameter("V_TEL_AGE", v_TEL_AGE) :
                new ObjectParameter("V_TEL_AGE", typeof(decimal));
    
            var v_ID_COMParameter = v_ID_COM.HasValue ?
                new ObjectParameter("V_ID_COM", v_ID_COM) :
                new ObjectParameter("V_ID_COM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARAGENCIAEXTERNA", v_NOM_AGEParameter, v_EMAIL_AGEParameter, v_TEL_AGEParameter, v_ID_COMParameter);
        }
    
        public virtual int SP_AGREGARARTICULO(string v_NOM_ARTI, Nullable<decimal> v_CANT_ARTI, string v_DETA_ARTI, Nullable<decimal> v_VALOR_ARTI, Nullable<decimal> v_ID_DEPTO)
        {
            var v_NOM_ARTIParameter = v_NOM_ARTI != null ?
                new ObjectParameter("V_NOM_ARTI", v_NOM_ARTI) :
                new ObjectParameter("V_NOM_ARTI", typeof(string));
    
            var v_CANT_ARTIParameter = v_CANT_ARTI.HasValue ?
                new ObjectParameter("V_CANT_ARTI", v_CANT_ARTI) :
                new ObjectParameter("V_CANT_ARTI", typeof(decimal));
    
            var v_DETA_ARTIParameter = v_DETA_ARTI != null ?
                new ObjectParameter("V_DETA_ARTI", v_DETA_ARTI) :
                new ObjectParameter("V_DETA_ARTI", typeof(string));
    
            var v_VALOR_ARTIParameter = v_VALOR_ARTI.HasValue ?
                new ObjectParameter("V_VALOR_ARTI", v_VALOR_ARTI) :
                new ObjectParameter("V_VALOR_ARTI", typeof(decimal));
    
            var v_ID_DEPTOParameter = v_ID_DEPTO.HasValue ?
                new ObjectParameter("V_ID_DEPTO", v_ID_DEPTO) :
                new ObjectParameter("V_ID_DEPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARARTICULO", v_NOM_ARTIParameter, v_CANT_ARTIParameter, v_DETA_ARTIParameter, v_VALOR_ARTIParameter, v_ID_DEPTOParameter);
        }
    
        public virtual int SP_AGREGARCHECKIN(Nullable<decimal> v_ID_RVA, string v_DETA_CHI, Nullable<decimal> v_ID_USR)
        {
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            var v_DETA_CHIParameter = v_DETA_CHI != null ?
                new ObjectParameter("V_DETA_CHI", v_DETA_CHI) :
                new ObjectParameter("V_DETA_CHI", typeof(string));
    
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARCHECKIN", v_ID_RVAParameter, v_DETA_CHIParameter, v_ID_USRParameter);
        }
    
        public virtual int SP_AGREGARCHECKOUT(Nullable<decimal> v_COST_MULTA, string v_DETA_CHO, Nullable<decimal> v_ID_RVA, Nullable<decimal> v_ID_USR)
        {
            var v_COST_MULTAParameter = v_COST_MULTA.HasValue ?
                new ObjectParameter("V_COST_MULTA", v_COST_MULTA) :
                new ObjectParameter("V_COST_MULTA", typeof(decimal));
    
            var v_DETA_CHOParameter = v_DETA_CHO != null ?
                new ObjectParameter("V_DETA_CHO", v_DETA_CHO) :
                new ObjectParameter("V_DETA_CHO", typeof(string));
    
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARCHECKOUT", v_COST_MULTAParameter, v_DETA_CHOParameter, v_ID_RVAParameter, v_ID_USRParameter);
        }
    
        public virtual int SP_AGREGARCOMUNA(string v_NOM_COM, Nullable<decimal> v_ID_RGN)
        {
            var v_NOM_COMParameter = v_NOM_COM != null ?
                new ObjectParameter("V_NOM_COM", v_NOM_COM) :
                new ObjectParameter("V_NOM_COM", typeof(string));
    
            var v_ID_RGNParameter = v_ID_RGN.HasValue ?
                new ObjectParameter("V_ID_RGN", v_ID_RGN) :
                new ObjectParameter("V_ID_RGN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARCOMUNA", v_NOM_COMParameter, v_ID_RGNParameter);
        }
    
        public virtual int SP_AGREGARCONDOMINIO(string v_NOM_CND, Nullable<decimal> v_ID_COM)
        {
            var v_NOM_CNDParameter = v_NOM_CND != null ?
                new ObjectParameter("V_NOM_CND", v_NOM_CND) :
                new ObjectParameter("V_NOM_CND", typeof(string));
    
            var v_ID_COMParameter = v_ID_COM.HasValue ?
                new ObjectParameter("V_ID_COM", v_ID_COM) :
                new ObjectParameter("V_ID_COM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARCONDOMINIO", v_NOM_CNDParameter, v_ID_COMParameter);
        }
    
        public virtual int SP_AGREGARCONDUCTOR(Nullable<decimal> v_RUT_CONDUC, string v_DV_CONDUC, string v_NOM_CONDUC, string v_APPAT_CONDUC, string v_APMAT_CONDUC, string v_EMAIL_CONDUC, Nullable<decimal> v_TEL_CONDUC, string v_PATENTE, Nullable<decimal> v_ID_SERV)
        {
            var v_RUT_CONDUCParameter = v_RUT_CONDUC.HasValue ?
                new ObjectParameter("V_RUT_CONDUC", v_RUT_CONDUC) :
                new ObjectParameter("V_RUT_CONDUC", typeof(decimal));
    
            var v_DV_CONDUCParameter = v_DV_CONDUC != null ?
                new ObjectParameter("V_DV_CONDUC", v_DV_CONDUC) :
                new ObjectParameter("V_DV_CONDUC", typeof(string));
    
            var v_NOM_CONDUCParameter = v_NOM_CONDUC != null ?
                new ObjectParameter("V_NOM_CONDUC", v_NOM_CONDUC) :
                new ObjectParameter("V_NOM_CONDUC", typeof(string));
    
            var v_APPAT_CONDUCParameter = v_APPAT_CONDUC != null ?
                new ObjectParameter("V_APPAT_CONDUC", v_APPAT_CONDUC) :
                new ObjectParameter("V_APPAT_CONDUC", typeof(string));
    
            var v_APMAT_CONDUCParameter = v_APMAT_CONDUC != null ?
                new ObjectParameter("V_APMAT_CONDUC", v_APMAT_CONDUC) :
                new ObjectParameter("V_APMAT_CONDUC", typeof(string));
    
            var v_EMAIL_CONDUCParameter = v_EMAIL_CONDUC != null ?
                new ObjectParameter("V_EMAIL_CONDUC", v_EMAIL_CONDUC) :
                new ObjectParameter("V_EMAIL_CONDUC", typeof(string));
    
            var v_TEL_CONDUCParameter = v_TEL_CONDUC.HasValue ?
                new ObjectParameter("V_TEL_CONDUC", v_TEL_CONDUC) :
                new ObjectParameter("V_TEL_CONDUC", typeof(decimal));
    
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARCONDUCTOR", v_RUT_CONDUCParameter, v_DV_CONDUCParameter, v_NOM_CONDUCParameter, v_APPAT_CONDUCParameter, v_APMAT_CONDUCParameter, v_EMAIL_CONDUCParameter, v_TEL_CONDUCParameter, v_PATENTEParameter, v_ID_SERVParameter);
        }
    
        public virtual int SP_AGREGARCONTSERV(Nullable<decimal> v_COSTO_TOTAL, string v_DETA_CONT, Nullable<System.DateTime> v_FEC_ACORD, string v_HORA_ACORD, string v_LUGAR_RECOGIDA, string v_LUGAR_DESTINO, Nullable<decimal> v_KM_REC, string v_EST_CONT, Nullable<decimal> v_ID_RVA, Nullable<decimal> v_ID_SERV)
        {
            var v_COSTO_TOTALParameter = v_COSTO_TOTAL.HasValue ?
                new ObjectParameter("V_COSTO_TOTAL", v_COSTO_TOTAL) :
                new ObjectParameter("V_COSTO_TOTAL", typeof(decimal));
    
            var v_DETA_CONTParameter = v_DETA_CONT != null ?
                new ObjectParameter("V_DETA_CONT", v_DETA_CONT) :
                new ObjectParameter("V_DETA_CONT", typeof(string));
    
            var v_FEC_ACORDParameter = v_FEC_ACORD.HasValue ?
                new ObjectParameter("V_FEC_ACORD", v_FEC_ACORD) :
                new ObjectParameter("V_FEC_ACORD", typeof(System.DateTime));
    
            var v_HORA_ACORDParameter = v_HORA_ACORD != null ?
                new ObjectParameter("V_HORA_ACORD", v_HORA_ACORD) :
                new ObjectParameter("V_HORA_ACORD", typeof(string));
    
            var v_LUGAR_RECOGIDAParameter = v_LUGAR_RECOGIDA != null ?
                new ObjectParameter("V_LUGAR_RECOGIDA", v_LUGAR_RECOGIDA) :
                new ObjectParameter("V_LUGAR_RECOGIDA", typeof(string));
    
            var v_LUGAR_DESTINOParameter = v_LUGAR_DESTINO != null ?
                new ObjectParameter("V_LUGAR_DESTINO", v_LUGAR_DESTINO) :
                new ObjectParameter("V_LUGAR_DESTINO", typeof(string));
    
            var v_KM_RECParameter = v_KM_REC.HasValue ?
                new ObjectParameter("V_KM_REC", v_KM_REC) :
                new ObjectParameter("V_KM_REC", typeof(decimal));
    
            var v_EST_CONTParameter = v_EST_CONT != null ?
                new ObjectParameter("V_EST_CONT", v_EST_CONT) :
                new ObjectParameter("V_EST_CONT", typeof(string));
    
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARCONTSERV", v_COSTO_TOTALParameter, v_DETA_CONTParameter, v_FEC_ACORDParameter, v_HORA_ACORDParameter, v_LUGAR_RECOGIDAParameter, v_LUGAR_DESTINOParameter, v_KM_RECParameter, v_EST_CONTParameter, v_ID_RVAParameter, v_ID_SERVParameter);
        }
    
        public virtual int SP_AGREGARDEPARTAMENTO(string v_DIR_DPTO, Nullable<decimal> v_NUM_DPTO, Nullable<decimal> v_N_AMB_DPTO, string v_DESC_DPTO, Nullable<decimal> v_COSTO_ARRI_DPTO, byte[] v_IMG_1_DPTO, byte[] v_IMG_2_DPTO, byte[] v_IMG_3_DPTO, byte[] v_IMG_4_DPTO, byte[] v_IMG_5_DPTO, Nullable<decimal> v_ID_CND)
        {
            var v_DIR_DPTOParameter = v_DIR_DPTO != null ?
                new ObjectParameter("V_DIR_DPTO", v_DIR_DPTO) :
                new ObjectParameter("V_DIR_DPTO", typeof(string));
    
            var v_NUM_DPTOParameter = v_NUM_DPTO.HasValue ?
                new ObjectParameter("V_NUM_DPTO", v_NUM_DPTO) :
                new ObjectParameter("V_NUM_DPTO", typeof(decimal));
    
            var v_N_AMB_DPTOParameter = v_N_AMB_DPTO.HasValue ?
                new ObjectParameter("V_N_AMB_DPTO", v_N_AMB_DPTO) :
                new ObjectParameter("V_N_AMB_DPTO", typeof(decimal));
    
            var v_DESC_DPTOParameter = v_DESC_DPTO != null ?
                new ObjectParameter("V_DESC_DPTO", v_DESC_DPTO) :
                new ObjectParameter("V_DESC_DPTO", typeof(string));
    
            var v_COSTO_ARRI_DPTOParameter = v_COSTO_ARRI_DPTO.HasValue ?
                new ObjectParameter("V_COSTO_ARRI_DPTO", v_COSTO_ARRI_DPTO) :
                new ObjectParameter("V_COSTO_ARRI_DPTO", typeof(decimal));
    
            var v_IMG_1_DPTOParameter = v_IMG_1_DPTO != null ?
                new ObjectParameter("V_IMG_1_DPTO", v_IMG_1_DPTO) :
                new ObjectParameter("V_IMG_1_DPTO", typeof(byte[]));
    
            var v_IMG_2_DPTOParameter = v_IMG_2_DPTO != null ?
                new ObjectParameter("V_IMG_2_DPTO", v_IMG_2_DPTO) :
                new ObjectParameter("V_IMG_2_DPTO", typeof(byte[]));
    
            var v_IMG_3_DPTOParameter = v_IMG_3_DPTO != null ?
                new ObjectParameter("V_IMG_3_DPTO", v_IMG_3_DPTO) :
                new ObjectParameter("V_IMG_3_DPTO", typeof(byte[]));
    
            var v_IMG_4_DPTOParameter = v_IMG_4_DPTO != null ?
                new ObjectParameter("V_IMG_4_DPTO", v_IMG_4_DPTO) :
                new ObjectParameter("V_IMG_4_DPTO", typeof(byte[]));
    
            var v_IMG_5_DPTOParameter = v_IMG_5_DPTO != null ?
                new ObjectParameter("V_IMG_5_DPTO", v_IMG_5_DPTO) :
                new ObjectParameter("V_IMG_5_DPTO", typeof(byte[]));
    
            var v_ID_CNDParameter = v_ID_CND.HasValue ?
                new ObjectParameter("V_ID_CND", v_ID_CND) :
                new ObjectParameter("V_ID_CND", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARDEPARTAMENTO", v_DIR_DPTOParameter, v_NUM_DPTOParameter, v_N_AMB_DPTOParameter, v_DESC_DPTOParameter, v_COSTO_ARRI_DPTOParameter, v_IMG_1_DPTOParameter, v_IMG_2_DPTOParameter, v_IMG_3_DPTOParameter, v_IMG_4_DPTOParameter, v_IMG_5_DPTOParameter, v_ID_CNDParameter);
        }
    
        public virtual int SP_AGREGARDISPONIBILIDAD(Nullable<System.DateTime> v_FEC_DISP, string v_ESTA_DISP, Nullable<decimal> v_ID_DPTO)
        {
            var v_FEC_DISPParameter = v_FEC_DISP.HasValue ?
                new ObjectParameter("V_FEC_DISP", v_FEC_DISP) :
                new ObjectParameter("V_FEC_DISP", typeof(System.DateTime));
    
            var v_ESTA_DISPParameter = v_ESTA_DISP != null ?
                new ObjectParameter("V_ESTA_DISP", v_ESTA_DISP) :
                new ObjectParameter("V_ESTA_DISP", typeof(string));
    
            var v_ID_DPTOParameter = v_ID_DPTO.HasValue ?
                new ObjectParameter("V_ID_DPTO", v_ID_DPTO) :
                new ObjectParameter("V_ID_DPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARDISPONIBILIDAD", v_FEC_DISPParameter, v_ESTA_DISPParameter, v_ID_DPTOParameter);
        }
    
        public virtual int SP_AGREGARGASTOS(Nullable<decimal> v_GAST_MES, Nullable<decimal> v_GAST_AGNO, Nullable<decimal> v_ID_DPTO)
        {
            var v_GAST_MESParameter = v_GAST_MES.HasValue ?
                new ObjectParameter("V_GAST_MES", v_GAST_MES) :
                new ObjectParameter("V_GAST_MES", typeof(decimal));
    
            var v_GAST_AGNOParameter = v_GAST_AGNO.HasValue ?
                new ObjectParameter("V_GAST_AGNO", v_GAST_AGNO) :
                new ObjectParameter("V_GAST_AGNO", typeof(decimal));
    
            var v_ID_DPTOParameter = v_ID_DPTO.HasValue ?
                new ObjectParameter("V_ID_DPTO", v_ID_DPTO) :
                new ObjectParameter("V_ID_DPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARGASTOS", v_GAST_MESParameter, v_GAST_AGNOParameter, v_ID_DPTOParameter);
        }
    
        public virtual int SP_AGREGARMANTENCION(Nullable<decimal> v_COST_MANT, string v_DETA_MANT, Nullable<decimal> v_ID_RMANT)
        {
            var v_COST_MANTParameter = v_COST_MANT.HasValue ?
                new ObjectParameter("V_COST_MANT", v_COST_MANT) :
                new ObjectParameter("V_COST_MANT", typeof(decimal));
    
            var v_DETA_MANTParameter = v_DETA_MANT != null ?
                new ObjectParameter("V_DETA_MANT", v_DETA_MANT) :
                new ObjectParameter("V_DETA_MANT", typeof(string));
    
            var v_ID_RMANTParameter = v_ID_RMANT.HasValue ?
                new ObjectParameter("V_ID_RMANT", v_ID_RMANT) :
                new ObjectParameter("V_ID_RMANT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARMANTENCION", v_COST_MANTParameter, v_DETA_MANTParameter, v_ID_RMANTParameter);
        }
    
        public virtual int SP_AGREGARMARCA(string v_NOMBRE_MARCA)
        {
            var v_NOMBRE_MARCAParameter = v_NOMBRE_MARCA != null ?
                new ObjectParameter("V_NOMBRE_MARCA", v_NOMBRE_MARCA) :
                new ObjectParameter("V_NOMBRE_MARCA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARMARCA", v_NOMBRE_MARCAParameter);
        }
    
        public virtual int SP_AGREGARMODELO(string v_NOMBRE_MODELO, Nullable<decimal> v_ID_MARCA)
        {
            var v_NOMBRE_MODELOParameter = v_NOMBRE_MODELO != null ?
                new ObjectParameter("V_NOMBRE_MODELO", v_NOMBRE_MODELO) :
                new ObjectParameter("V_NOMBRE_MODELO", typeof(string));
    
            var v_ID_MARCAParameter = v_ID_MARCA.HasValue ?
                new ObjectParameter("V_ID_MARCA", v_ID_MARCA) :
                new ObjectParameter("V_ID_MARCA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARMODELO", v_NOMBRE_MODELOParameter, v_ID_MARCAParameter);
        }
    
        public virtual int SP_AGREGARPAGO(Nullable<decimal> v_ID_RVA, Nullable<decimal> v_MONTO_PAGADO)
        {
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            var v_MONTO_PAGADOParameter = v_MONTO_PAGADO.HasValue ?
                new ObjectParameter("V_MONTO_PAGADO", v_MONTO_PAGADO) :
                new ObjectParameter("V_MONTO_PAGADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARPAGO", v_ID_RVAParameter, v_MONTO_PAGADOParameter);
        }
    
        public virtual int SP_AGREGARREGION(string v_NOM_RGN)
        {
            var v_NOM_RGNParameter = v_NOM_RGN != null ?
                new ObjectParameter("V_NOM_RGN", v_NOM_RGN) :
                new ObjectParameter("V_NOM_RGN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARREGION", v_NOM_RGNParameter);
        }
    
        public virtual int SP_AGREGARRESERVA(Nullable<System.DateTime> v_FEC_INI_RVA, Nullable<System.DateTime> v_FEC_FIN_RVA, Nullable<decimal> v_NUM_PERS, Nullable<decimal> v_ID_DPTO, Nullable<decimal> v_ID_USR)
        {
            var v_FEC_INI_RVAParameter = v_FEC_INI_RVA.HasValue ?
                new ObjectParameter("V_FEC_INI_RVA", v_FEC_INI_RVA) :
                new ObjectParameter("V_FEC_INI_RVA", typeof(System.DateTime));
    
            var v_FEC_FIN_RVAParameter = v_FEC_FIN_RVA.HasValue ?
                new ObjectParameter("V_FEC_FIN_RVA", v_FEC_FIN_RVA) :
                new ObjectParameter("V_FEC_FIN_RVA", typeof(System.DateTime));
    
            var v_NUM_PERSParameter = v_NUM_PERS.HasValue ?
                new ObjectParameter("V_NUM_PERS", v_NUM_PERS) :
                new ObjectParameter("V_NUM_PERS", typeof(decimal));
    
            var v_ID_DPTOParameter = v_ID_DPTO.HasValue ?
                new ObjectParameter("V_ID_DPTO", v_ID_DPTO) :
                new ObjectParameter("V_ID_DPTO", typeof(decimal));
    
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARRESERVA", v_FEC_INI_RVAParameter, v_FEC_FIN_RVAParameter, v_NUM_PERSParameter, v_ID_DPTOParameter, v_ID_USRParameter);
        }
    
        public virtual int SP_AGREGARRESMANT(Nullable<System.DateTime> v_FEC_RMANT, Nullable<decimal> v_ID_DPTO, Nullable<decimal> v_ID_USR)
        {
            var v_FEC_RMANTParameter = v_FEC_RMANT.HasValue ?
                new ObjectParameter("V_FEC_RMANT", v_FEC_RMANT) :
                new ObjectParameter("V_FEC_RMANT", typeof(System.DateTime));
    
            var v_ID_DPTOParameter = v_ID_DPTO.HasValue ?
                new ObjectParameter("V_ID_DPTO", v_ID_DPTO) :
                new ObjectParameter("V_ID_DPTO", typeof(decimal));
    
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARRESMANT", v_FEC_RMANTParameter, v_ID_DPTOParameter, v_ID_USRParameter);
        }
    
        public virtual int SP_AGREGARSERVEXTRAS(string v_NOM_SERV, string v_TIPO_SERV, string v_DESC_SERV, Nullable<decimal> v_ID_AGENCIA)
        {
            var v_NOM_SERVParameter = v_NOM_SERV != null ?
                new ObjectParameter("V_NOM_SERV", v_NOM_SERV) :
                new ObjectParameter("V_NOM_SERV", typeof(string));
    
            var v_TIPO_SERVParameter = v_TIPO_SERV != null ?
                new ObjectParameter("V_TIPO_SERV", v_TIPO_SERV) :
                new ObjectParameter("V_TIPO_SERV", typeof(string));
    
            var v_DESC_SERVParameter = v_DESC_SERV != null ?
                new ObjectParameter("V_DESC_SERV", v_DESC_SERV) :
                new ObjectParameter("V_DESC_SERV", typeof(string));
    
            var v_ID_AGENCIAParameter = v_ID_AGENCIA.HasValue ?
                new ObjectParameter("V_ID_AGENCIA", v_ID_AGENCIA) :
                new ObjectParameter("V_ID_AGENCIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARSERVEXTRAS", v_NOM_SERVParameter, v_TIPO_SERVParameter, v_DESC_SERVParameter, v_ID_AGENCIAParameter);
        }
    
        public virtual int SP_AGREGARTOUR(Nullable<decimal> v_ID_SERV, Nullable<decimal> v_DUR_HRA, Nullable<decimal> v_DUR_MIN, Nullable<decimal> v_COST_ADULT, Nullable<decimal> v_COSTO_NIGNO, Nullable<decimal> v_COSTO_3RA, string v_UBI_PARTIDA, string v_UBI_FIN, string v_ALIMENTACION, string v_TRANSPORTE)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            var v_DUR_HRAParameter = v_DUR_HRA.HasValue ?
                new ObjectParameter("V_DUR_HRA", v_DUR_HRA) :
                new ObjectParameter("V_DUR_HRA", typeof(decimal));
    
            var v_DUR_MINParameter = v_DUR_MIN.HasValue ?
                new ObjectParameter("V_DUR_MIN", v_DUR_MIN) :
                new ObjectParameter("V_DUR_MIN", typeof(decimal));
    
            var v_COST_ADULTParameter = v_COST_ADULT.HasValue ?
                new ObjectParameter("V_COST_ADULT", v_COST_ADULT) :
                new ObjectParameter("V_COST_ADULT", typeof(decimal));
    
            var v_COSTO_NIGNOParameter = v_COSTO_NIGNO.HasValue ?
                new ObjectParameter("V_COSTO_NIGNO", v_COSTO_NIGNO) :
                new ObjectParameter("V_COSTO_NIGNO", typeof(decimal));
    
            var v_COSTO_3RAParameter = v_COSTO_3RA.HasValue ?
                new ObjectParameter("V_COSTO_3RA", v_COSTO_3RA) :
                new ObjectParameter("V_COSTO_3RA", typeof(decimal));
    
            var v_UBI_PARTIDAParameter = v_UBI_PARTIDA != null ?
                new ObjectParameter("V_UBI_PARTIDA", v_UBI_PARTIDA) :
                new ObjectParameter("V_UBI_PARTIDA", typeof(string));
    
            var v_UBI_FINParameter = v_UBI_FIN != null ?
                new ObjectParameter("V_UBI_FIN", v_UBI_FIN) :
                new ObjectParameter("V_UBI_FIN", typeof(string));
    
            var v_ALIMENTACIONParameter = v_ALIMENTACION != null ?
                new ObjectParameter("V_ALIMENTACION", v_ALIMENTACION) :
                new ObjectParameter("V_ALIMENTACION", typeof(string));
    
            var v_TRANSPORTEParameter = v_TRANSPORTE != null ?
                new ObjectParameter("V_TRANSPORTE", v_TRANSPORTE) :
                new ObjectParameter("V_TRANSPORTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARTOUR", v_ID_SERVParameter, v_DUR_HRAParameter, v_DUR_MINParameter, v_COST_ADULTParameter, v_COSTO_NIGNOParameter, v_COSTO_3RAParameter, v_UBI_PARTIDAParameter, v_UBI_FINParameter, v_ALIMENTACIONParameter, v_TRANSPORTEParameter);
        }
    
        public virtual int SP_AGREGARTRANSPORTE(Nullable<decimal> v_ID_SERV, Nullable<decimal> v_COST_KM_DIA, Nullable<decimal> v_COST_KM_NOC)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            var v_COST_KM_DIAParameter = v_COST_KM_DIA.HasValue ?
                new ObjectParameter("V_COST_KM_DIA", v_COST_KM_DIA) :
                new ObjectParameter("V_COST_KM_DIA", typeof(decimal));
    
            var v_COST_KM_NOCParameter = v_COST_KM_NOC.HasValue ?
                new ObjectParameter("V_COST_KM_NOC", v_COST_KM_NOC) :
                new ObjectParameter("V_COST_KM_NOC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARTRANSPORTE", v_ID_SERVParameter, v_COST_KM_DIAParameter, v_COST_KM_NOCParameter);
        }
    
        public virtual int SP_AGREGARUSR(string v_EMAIL_USR, string v_CONTR_USR, string v_NOM_USR, string v_APPAT_USR, string v_APMAT_USR, Nullable<decimal> v_TEL_USR, Nullable<decimal> v_RUT_USR, string v_DV_USR, Nullable<decimal> v_CANT_RES, string v_EST_CTA, string v_TIPO_CLI, Nullable<decimal> v_ID_TIPO_USR)
        {
            var v_EMAIL_USRParameter = v_EMAIL_USR != null ?
                new ObjectParameter("V_EMAIL_USR", v_EMAIL_USR) :
                new ObjectParameter("V_EMAIL_USR", typeof(string));
    
            var v_CONTR_USRParameter = v_CONTR_USR != null ?
                new ObjectParameter("V_CONTR_USR", v_CONTR_USR) :
                new ObjectParameter("V_CONTR_USR", typeof(string));
    
            var v_NOM_USRParameter = v_NOM_USR != null ?
                new ObjectParameter("V_NOM_USR", v_NOM_USR) :
                new ObjectParameter("V_NOM_USR", typeof(string));
    
            var v_APPAT_USRParameter = v_APPAT_USR != null ?
                new ObjectParameter("V_APPAT_USR", v_APPAT_USR) :
                new ObjectParameter("V_APPAT_USR", typeof(string));
    
            var v_APMAT_USRParameter = v_APMAT_USR != null ?
                new ObjectParameter("V_APMAT_USR", v_APMAT_USR) :
                new ObjectParameter("V_APMAT_USR", typeof(string));
    
            var v_TEL_USRParameter = v_TEL_USR.HasValue ?
                new ObjectParameter("V_TEL_USR", v_TEL_USR) :
                new ObjectParameter("V_TEL_USR", typeof(decimal));
    
            var v_RUT_USRParameter = v_RUT_USR.HasValue ?
                new ObjectParameter("V_RUT_USR", v_RUT_USR) :
                new ObjectParameter("V_RUT_USR", typeof(decimal));
    
            var v_DV_USRParameter = v_DV_USR != null ?
                new ObjectParameter("V_DV_USR", v_DV_USR) :
                new ObjectParameter("V_DV_USR", typeof(string));
    
            var v_CANT_RESParameter = v_CANT_RES.HasValue ?
                new ObjectParameter("V_CANT_RES", v_CANT_RES) :
                new ObjectParameter("V_CANT_RES", typeof(decimal));
    
            var v_EST_CTAParameter = v_EST_CTA != null ?
                new ObjectParameter("V_EST_CTA", v_EST_CTA) :
                new ObjectParameter("V_EST_CTA", typeof(string));
    
            var v_TIPO_CLIParameter = v_TIPO_CLI != null ?
                new ObjectParameter("V_TIPO_CLI", v_TIPO_CLI) :
                new ObjectParameter("V_TIPO_CLI", typeof(string));
    
            var v_ID_TIPO_USRParameter = v_ID_TIPO_USR.HasValue ?
                new ObjectParameter("V_ID_TIPO_USR", v_ID_TIPO_USR) :
                new ObjectParameter("V_ID_TIPO_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARUSR", v_EMAIL_USRParameter, v_CONTR_USRParameter, v_NOM_USRParameter, v_APPAT_USRParameter, v_APMAT_USRParameter, v_TEL_USRParameter, v_RUT_USRParameter, v_DV_USRParameter, v_CANT_RESParameter, v_EST_CTAParameter, v_TIPO_CLIParameter, v_ID_TIPO_USRParameter);
        }
    
        public virtual int SP_AGREGARVEHICULO(string v_PATENTE, string v_COLOR, Nullable<System.DateTime> v_AGNO, Nullable<decimal> v_CANT_PUERTAS, Nullable<decimal> v_CAP_PASAJ, Nullable<decimal> v_CAP_MALE, string v_ASIENTO_NIGNO, string v_PER_SILLA, Nullable<decimal> v_ID_MODELO)
        {
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_COLORParameter = v_COLOR != null ?
                new ObjectParameter("V_COLOR", v_COLOR) :
                new ObjectParameter("V_COLOR", typeof(string));
    
            var v_AGNOParameter = v_AGNO.HasValue ?
                new ObjectParameter("V_AGNO", v_AGNO) :
                new ObjectParameter("V_AGNO", typeof(System.DateTime));
    
            var v_CANT_PUERTASParameter = v_CANT_PUERTAS.HasValue ?
                new ObjectParameter("V_CANT_PUERTAS", v_CANT_PUERTAS) :
                new ObjectParameter("V_CANT_PUERTAS", typeof(decimal));
    
            var v_CAP_PASAJParameter = v_CAP_PASAJ.HasValue ?
                new ObjectParameter("V_CAP_PASAJ", v_CAP_PASAJ) :
                new ObjectParameter("V_CAP_PASAJ", typeof(decimal));
    
            var v_CAP_MALEParameter = v_CAP_MALE.HasValue ?
                new ObjectParameter("V_CAP_MALE", v_CAP_MALE) :
                new ObjectParameter("V_CAP_MALE", typeof(decimal));
    
            var v_ASIENTO_NIGNOParameter = v_ASIENTO_NIGNO != null ?
                new ObjectParameter("V_ASIENTO_NIGNO", v_ASIENTO_NIGNO) :
                new ObjectParameter("V_ASIENTO_NIGNO", typeof(string));
    
            var v_PER_SILLAParameter = v_PER_SILLA != null ?
                new ObjectParameter("V_PER_SILLA", v_PER_SILLA) :
                new ObjectParameter("V_PER_SILLA", typeof(string));
    
            var v_ID_MODELOParameter = v_ID_MODELO.HasValue ?
                new ObjectParameter("V_ID_MODELO", v_ID_MODELO) :
                new ObjectParameter("V_ID_MODELO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AGREGARVEHICULO", v_PATENTEParameter, v_COLORParameter, v_AGNOParameter, v_CANT_PUERTASParameter, v_CAP_PASAJParameter, v_CAP_MALEParameter, v_ASIENTO_NIGNOParameter, v_PER_SILLAParameter, v_ID_MODELOParameter);
        }
    
        public virtual int SP_CAMBIARTIPOCLIENTE(Nullable<decimal> v_ID_USR)
        {
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAMBIARTIPOCLIENTE", v_ID_USRParameter);
        }
    
        public virtual int SP_ELIMINARAGENCIAEXTERNA(Nullable<decimal> v_ID_AGENCIA)
        {
            var v_ID_AGENCIAParameter = v_ID_AGENCIA.HasValue ?
                new ObjectParameter("V_ID_AGENCIA", v_ID_AGENCIA) :
                new ObjectParameter("V_ID_AGENCIA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARAGENCIAEXTERNA", v_ID_AGENCIAParameter);
        }
    
        public virtual int SP_ELIMINARARTICULO(Nullable<decimal> v_ID_ARTI)
        {
            var v_ID_ARTIParameter = v_ID_ARTI.HasValue ?
                new ObjectParameter("V_ID_ARTI", v_ID_ARTI) :
                new ObjectParameter("V_ID_ARTI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARARTICULO", v_ID_ARTIParameter);
        }
    
        public virtual int SP_ELIMINARCOMUNA(Nullable<decimal> v_ID_COM)
        {
            var v_ID_COMParameter = v_ID_COM.HasValue ?
                new ObjectParameter("V_ID_COM", v_ID_COM) :
                new ObjectParameter("V_ID_COM", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARCOMUNA", v_ID_COMParameter);
        }
    
        public virtual int SP_ELIMINARCONDOMINIO(Nullable<decimal> v_ID_CND)
        {
            var v_ID_CNDParameter = v_ID_CND.HasValue ?
                new ObjectParameter("V_ID_CND", v_ID_CND) :
                new ObjectParameter("V_ID_CND", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARCONDOMINIO", v_ID_CNDParameter);
        }
    
        public virtual int SP_ELIMINARCONDUCTOR(Nullable<decimal> v_RUT_CONDUC)
        {
            var v_RUT_CONDUCParameter = v_RUT_CONDUC.HasValue ?
                new ObjectParameter("V_RUT_CONDUC", v_RUT_CONDUC) :
                new ObjectParameter("V_RUT_CONDUC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARCONDUCTOR", v_RUT_CONDUCParameter);
        }
    
        public virtual int SP_ELIMINARCONTSERV(Nullable<decimal> v_ID_CONT_SERV)
        {
            var v_ID_CONT_SERVParameter = v_ID_CONT_SERV.HasValue ?
                new ObjectParameter("V_ID_CONT_SERV", v_ID_CONT_SERV) :
                new ObjectParameter("V_ID_CONT_SERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARCONTSERV", v_ID_CONT_SERVParameter);
        }
    
        public virtual int SP_ELIMINARDEPARTAMENTO(Nullable<decimal> v_ID_DPTO)
        {
            var v_ID_DPTOParameter = v_ID_DPTO.HasValue ?
                new ObjectParameter("V_ID_DPTO", v_ID_DPTO) :
                new ObjectParameter("V_ID_DPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARDEPARTAMENTO", v_ID_DPTOParameter);
        }
    
        public virtual int SP_ELIMINARGASTOS(Nullable<decimal> v_ID_DPTO)
        {
            var v_ID_DPTOParameter = v_ID_DPTO.HasValue ?
                new ObjectParameter("V_ID_DPTO", v_ID_DPTO) :
                new ObjectParameter("V_ID_DPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARGASTOS", v_ID_DPTOParameter);
        }
    
        public virtual int SP_ELIMINARMANTENCION(Nullable<decimal> v_ID_RMANT)
        {
            var v_ID_RMANTParameter = v_ID_RMANT.HasValue ?
                new ObjectParameter("V_ID_RMANT", v_ID_RMANT) :
                new ObjectParameter("V_ID_RMANT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARMANTENCION", v_ID_RMANTParameter);
        }
    
        public virtual int SP_ELIMINARMARCA(Nullable<decimal> v_ID_MARCA)
        {
            var v_ID_MARCAParameter = v_ID_MARCA.HasValue ?
                new ObjectParameter("V_ID_MARCA", v_ID_MARCA) :
                new ObjectParameter("V_ID_MARCA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARMARCA", v_ID_MARCAParameter);
        }
    
        public virtual int SP_ELIMINARMODELO(Nullable<decimal> v_ID_MODELO)
        {
            var v_ID_MODELOParameter = v_ID_MODELO.HasValue ?
                new ObjectParameter("V_ID_MODELO", v_ID_MODELO) :
                new ObjectParameter("V_ID_MODELO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARMODELO", v_ID_MODELOParameter);
        }
    
        public virtual int SP_ELIMINARPAGO(Nullable<decimal> v_ID_RVA)
        {
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARPAGO", v_ID_RVAParameter);
        }
    
        public virtual int SP_ELIMINARREGION(Nullable<decimal> v_ID_RGN)
        {
            var v_ID_RGNParameter = v_ID_RGN.HasValue ?
                new ObjectParameter("V_ID_RGN", v_ID_RGN) :
                new ObjectParameter("V_ID_RGN", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARREGION", v_ID_RGNParameter);
        }
    
        public virtual int SP_ELIMINARRESERVA(Nullable<decimal> v_ID_RVA)
        {
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARRESERVA", v_ID_RVAParameter);
        }
    
        public virtual int SP_ELIMINARRESMANT(Nullable<decimal> v_ID_RMANT)
        {
            var v_ID_RMANTParameter = v_ID_RMANT.HasValue ?
                new ObjectParameter("V_ID_RMANT", v_ID_RMANT) :
                new ObjectParameter("V_ID_RMANT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARRESMANT", v_ID_RMANTParameter);
        }
    
        public virtual int SP_ELIMINARSEREXTRAS(Nullable<decimal> v_ID_SERV)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARSEREXTRAS", v_ID_SERVParameter);
        }
    
        public virtual int SP_ELIMINARSERVEXTRAS(Nullable<decimal> v_ID_SERV)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARSERVEXTRAS", v_ID_SERVParameter);
        }
    
        public virtual int SP_ELIMINARTOUR(Nullable<decimal> v_ID_SERV)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARTOUR", v_ID_SERVParameter);
        }
    
        public virtual int SP_ELIMINARTRANSPORTE(Nullable<decimal> v_ID_SERV)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARTRANSPORTE", v_ID_SERVParameter);
        }
    
        public virtual int SP_ELIMINARUSR(Nullable<decimal> v_ID_USR)
        {
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARUSR", v_ID_USRParameter);
        }
    
        public virtual int SP_ELIMINARVEHICULO(string v_PATENTE)
        {
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINARVEHICULO", v_PATENTEParameter);
        }
    
        public virtual int SP_MODIFICARAGENCIAEXTERNA(Nullable<decimal> v_ID_AGE, string v_NOM_AGE, string v_EMAIL_AGE, Nullable<decimal> v_TEL_AGE)
        {
            var v_ID_AGEParameter = v_ID_AGE.HasValue ?
                new ObjectParameter("V_ID_AGE", v_ID_AGE) :
                new ObjectParameter("V_ID_AGE", typeof(decimal));
    
            var v_NOM_AGEParameter = v_NOM_AGE != null ?
                new ObjectParameter("V_NOM_AGE", v_NOM_AGE) :
                new ObjectParameter("V_NOM_AGE", typeof(string));
    
            var v_EMAIL_AGEParameter = v_EMAIL_AGE != null ?
                new ObjectParameter("V_EMAIL_AGE", v_EMAIL_AGE) :
                new ObjectParameter("V_EMAIL_AGE", typeof(string));
    
            var v_TEL_AGEParameter = v_TEL_AGE.HasValue ?
                new ObjectParameter("V_TEL_AGE", v_TEL_AGE) :
                new ObjectParameter("V_TEL_AGE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARAGENCIAEXTERNA", v_ID_AGEParameter, v_NOM_AGEParameter, v_EMAIL_AGEParameter, v_TEL_AGEParameter);
        }
    
        public virtual int SP_MODIFICARARTICULO(Nullable<decimal> v_ID_ARTI, string v_NOM_ARTI, Nullable<decimal> v_CANT_ARTI, string v_DETA_ARTI, Nullable<decimal> v_VALOR_ARTI)
        {
            var v_ID_ARTIParameter = v_ID_ARTI.HasValue ?
                new ObjectParameter("V_ID_ARTI", v_ID_ARTI) :
                new ObjectParameter("V_ID_ARTI", typeof(decimal));
    
            var v_NOM_ARTIParameter = v_NOM_ARTI != null ?
                new ObjectParameter("V_NOM_ARTI", v_NOM_ARTI) :
                new ObjectParameter("V_NOM_ARTI", typeof(string));
    
            var v_CANT_ARTIParameter = v_CANT_ARTI.HasValue ?
                new ObjectParameter("V_CANT_ARTI", v_CANT_ARTI) :
                new ObjectParameter("V_CANT_ARTI", typeof(decimal));
    
            var v_DETA_ARTIParameter = v_DETA_ARTI != null ?
                new ObjectParameter("V_DETA_ARTI", v_DETA_ARTI) :
                new ObjectParameter("V_DETA_ARTI", typeof(string));
    
            var v_VALOR_ARTIParameter = v_VALOR_ARTI.HasValue ?
                new ObjectParameter("V_VALOR_ARTI", v_VALOR_ARTI) :
                new ObjectParameter("V_VALOR_ARTI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARARTICULO", v_ID_ARTIParameter, v_NOM_ARTIParameter, v_CANT_ARTIParameter, v_DETA_ARTIParameter, v_VALOR_ARTIParameter);
        }
    
        public virtual int SP_MODIFICARCHECKIN(Nullable<decimal> v_ID_RVA, string v_DETA_CHI)
        {
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            var v_DETA_CHIParameter = v_DETA_CHI != null ?
                new ObjectParameter("V_DETA_CHI", v_DETA_CHI) :
                new ObjectParameter("V_DETA_CHI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARCHECKIN", v_ID_RVAParameter, v_DETA_CHIParameter);
        }
    
        public virtual int SP_MODIFICARCHECKOUT(Nullable<decimal> v_COST_MULTA, string v_DETA_CHO, Nullable<decimal> v_ID_RVA)
        {
            var v_COST_MULTAParameter = v_COST_MULTA.HasValue ?
                new ObjectParameter("V_COST_MULTA", v_COST_MULTA) :
                new ObjectParameter("V_COST_MULTA", typeof(decimal));
    
            var v_DETA_CHOParameter = v_DETA_CHO != null ?
                new ObjectParameter("V_DETA_CHO", v_DETA_CHO) :
                new ObjectParameter("V_DETA_CHO", typeof(string));
    
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARCHECKOUT", v_COST_MULTAParameter, v_DETA_CHOParameter, v_ID_RVAParameter);
        }
    
        public virtual int SP_MODIFICARCOMUNA(Nullable<decimal> v_ID_COM, string v_NOM_COM)
        {
            var v_ID_COMParameter = v_ID_COM.HasValue ?
                new ObjectParameter("V_ID_COM", v_ID_COM) :
                new ObjectParameter("V_ID_COM", typeof(decimal));
    
            var v_NOM_COMParameter = v_NOM_COM != null ?
                new ObjectParameter("V_NOM_COM", v_NOM_COM) :
                new ObjectParameter("V_NOM_COM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARCOMUNA", v_ID_COMParameter, v_NOM_COMParameter);
        }
    
        public virtual int SP_MODIFICARCONDOMINIO(Nullable<decimal> v_ID_CND, string v_NOM_CND)
        {
            var v_ID_CNDParameter = v_ID_CND.HasValue ?
                new ObjectParameter("V_ID_CND", v_ID_CND) :
                new ObjectParameter("V_ID_CND", typeof(decimal));
    
            var v_NOM_CNDParameter = v_NOM_CND != null ?
                new ObjectParameter("V_NOM_CND", v_NOM_CND) :
                new ObjectParameter("V_NOM_CND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARCONDOMINIO", v_ID_CNDParameter, v_NOM_CNDParameter);
        }
    
        public virtual int SP_MODIFICARCONDUCTOR(Nullable<decimal> v_RUT_CONDUC, string v_DV_CONDUC, string v_NOM_CONDUC, string v_APPAT_CONDUC, string v_APMAT_CONDUC, string v_EMAIL_CONDUC, Nullable<decimal> v_TEL_CONDUC)
        {
            var v_RUT_CONDUCParameter = v_RUT_CONDUC.HasValue ?
                new ObjectParameter("V_RUT_CONDUC", v_RUT_CONDUC) :
                new ObjectParameter("V_RUT_CONDUC", typeof(decimal));
    
            var v_DV_CONDUCParameter = v_DV_CONDUC != null ?
                new ObjectParameter("V_DV_CONDUC", v_DV_CONDUC) :
                new ObjectParameter("V_DV_CONDUC", typeof(string));
    
            var v_NOM_CONDUCParameter = v_NOM_CONDUC != null ?
                new ObjectParameter("V_NOM_CONDUC", v_NOM_CONDUC) :
                new ObjectParameter("V_NOM_CONDUC", typeof(string));
    
            var v_APPAT_CONDUCParameter = v_APPAT_CONDUC != null ?
                new ObjectParameter("V_APPAT_CONDUC", v_APPAT_CONDUC) :
                new ObjectParameter("V_APPAT_CONDUC", typeof(string));
    
            var v_APMAT_CONDUCParameter = v_APMAT_CONDUC != null ?
                new ObjectParameter("V_APMAT_CONDUC", v_APMAT_CONDUC) :
                new ObjectParameter("V_APMAT_CONDUC", typeof(string));
    
            var v_EMAIL_CONDUCParameter = v_EMAIL_CONDUC != null ?
                new ObjectParameter("V_EMAIL_CONDUC", v_EMAIL_CONDUC) :
                new ObjectParameter("V_EMAIL_CONDUC", typeof(string));
    
            var v_TEL_CONDUCParameter = v_TEL_CONDUC.HasValue ?
                new ObjectParameter("V_TEL_CONDUC", v_TEL_CONDUC) :
                new ObjectParameter("V_TEL_CONDUC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARCONDUCTOR", v_RUT_CONDUCParameter, v_DV_CONDUCParameter, v_NOM_CONDUCParameter, v_APPAT_CONDUCParameter, v_APMAT_CONDUCParameter, v_EMAIL_CONDUCParameter, v_TEL_CONDUCParameter);
        }
    
        public virtual int SP_MODIFICARCONTSERV(Nullable<decimal> v_ID_CONT_SERV, Nullable<System.DateTime> v_FEC_CONT, Nullable<decimal> v_COSTO_TOTAL, string v_DETA_CONT, Nullable<System.DateTime> v_FEC_ACORD, string v_HORA_ACORD, string v_LUGAR_RECOGIDA, string v_LUGAR_DESTINO, Nullable<decimal> v_KM_REC, string v_EST_CONT)
        {
            var v_ID_CONT_SERVParameter = v_ID_CONT_SERV.HasValue ?
                new ObjectParameter("V_ID_CONT_SERV", v_ID_CONT_SERV) :
                new ObjectParameter("V_ID_CONT_SERV", typeof(decimal));
    
            var v_FEC_CONTParameter = v_FEC_CONT.HasValue ?
                new ObjectParameter("V_FEC_CONT", v_FEC_CONT) :
                new ObjectParameter("V_FEC_CONT", typeof(System.DateTime));
    
            var v_COSTO_TOTALParameter = v_COSTO_TOTAL.HasValue ?
                new ObjectParameter("V_COSTO_TOTAL", v_COSTO_TOTAL) :
                new ObjectParameter("V_COSTO_TOTAL", typeof(decimal));
    
            var v_DETA_CONTParameter = v_DETA_CONT != null ?
                new ObjectParameter("V_DETA_CONT", v_DETA_CONT) :
                new ObjectParameter("V_DETA_CONT", typeof(string));
    
            var v_FEC_ACORDParameter = v_FEC_ACORD.HasValue ?
                new ObjectParameter("V_FEC_ACORD", v_FEC_ACORD) :
                new ObjectParameter("V_FEC_ACORD", typeof(System.DateTime));
    
            var v_HORA_ACORDParameter = v_HORA_ACORD != null ?
                new ObjectParameter("V_HORA_ACORD", v_HORA_ACORD) :
                new ObjectParameter("V_HORA_ACORD", typeof(string));
    
            var v_LUGAR_RECOGIDAParameter = v_LUGAR_RECOGIDA != null ?
                new ObjectParameter("V_LUGAR_RECOGIDA", v_LUGAR_RECOGIDA) :
                new ObjectParameter("V_LUGAR_RECOGIDA", typeof(string));
    
            var v_LUGAR_DESTINOParameter = v_LUGAR_DESTINO != null ?
                new ObjectParameter("V_LUGAR_DESTINO", v_LUGAR_DESTINO) :
                new ObjectParameter("V_LUGAR_DESTINO", typeof(string));
    
            var v_KM_RECParameter = v_KM_REC.HasValue ?
                new ObjectParameter("V_KM_REC", v_KM_REC) :
                new ObjectParameter("V_KM_REC", typeof(decimal));
    
            var v_EST_CONTParameter = v_EST_CONT != null ?
                new ObjectParameter("V_EST_CONT", v_EST_CONT) :
                new ObjectParameter("V_EST_CONT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARCONTSERV", v_ID_CONT_SERVParameter, v_FEC_CONTParameter, v_COSTO_TOTALParameter, v_DETA_CONTParameter, v_FEC_ACORDParameter, v_HORA_ACORDParameter, v_LUGAR_RECOGIDAParameter, v_LUGAR_DESTINOParameter, v_KM_RECParameter, v_EST_CONTParameter);
        }
    
        public virtual int SP_MODIFICARDATOSUSR(Nullable<decimal> v_ID_USR, string v_EMAIL_USR, string v_CONTR_USR, Nullable<decimal> v_TEL_USR)
        {
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            var v_EMAIL_USRParameter = v_EMAIL_USR != null ?
                new ObjectParameter("V_EMAIL_USR", v_EMAIL_USR) :
                new ObjectParameter("V_EMAIL_USR", typeof(string));
    
            var v_CONTR_USRParameter = v_CONTR_USR != null ?
                new ObjectParameter("V_CONTR_USR", v_CONTR_USR) :
                new ObjectParameter("V_CONTR_USR", typeof(string));
    
            var v_TEL_USRParameter = v_TEL_USR.HasValue ?
                new ObjectParameter("V_TEL_USR", v_TEL_USR) :
                new ObjectParameter("V_TEL_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARDATOSUSR", v_ID_USRParameter, v_EMAIL_USRParameter, v_CONTR_USRParameter, v_TEL_USRParameter);
        }
    
        public virtual int SP_MODIFICARDEPARTAMENTO(Nullable<decimal> v_ID_DPTO, string v_DIR_DPTO, Nullable<decimal> v_NUM_DPTO, Nullable<decimal> v_N_AMB_DPTO, string v_DESC_DPTO, Nullable<decimal> v_COSTO_ARRI_DPTO, byte[] v_IMG_1_DPTO, byte[] v_IMG_2_DPTO, byte[] v_IMG_3_DPTO, byte[] v_IMG_4_DPTO, byte[] v_IMG_5_DPTO)
        {
            var v_ID_DPTOParameter = v_ID_DPTO.HasValue ?
                new ObjectParameter("V_ID_DPTO", v_ID_DPTO) :
                new ObjectParameter("V_ID_DPTO", typeof(decimal));
    
            var v_DIR_DPTOParameter = v_DIR_DPTO != null ?
                new ObjectParameter("V_DIR_DPTO", v_DIR_DPTO) :
                new ObjectParameter("V_DIR_DPTO", typeof(string));
    
            var v_NUM_DPTOParameter = v_NUM_DPTO.HasValue ?
                new ObjectParameter("V_NUM_DPTO", v_NUM_DPTO) :
                new ObjectParameter("V_NUM_DPTO", typeof(decimal));
    
            var v_N_AMB_DPTOParameter = v_N_AMB_DPTO.HasValue ?
                new ObjectParameter("V_N_AMB_DPTO", v_N_AMB_DPTO) :
                new ObjectParameter("V_N_AMB_DPTO", typeof(decimal));
    
            var v_DESC_DPTOParameter = v_DESC_DPTO != null ?
                new ObjectParameter("V_DESC_DPTO", v_DESC_DPTO) :
                new ObjectParameter("V_DESC_DPTO", typeof(string));
    
            var v_COSTO_ARRI_DPTOParameter = v_COSTO_ARRI_DPTO.HasValue ?
                new ObjectParameter("V_COSTO_ARRI_DPTO", v_COSTO_ARRI_DPTO) :
                new ObjectParameter("V_COSTO_ARRI_DPTO", typeof(decimal));
    
            var v_IMG_1_DPTOParameter = v_IMG_1_DPTO != null ?
                new ObjectParameter("V_IMG_1_DPTO", v_IMG_1_DPTO) :
                new ObjectParameter("V_IMG_1_DPTO", typeof(byte[]));
    
            var v_IMG_2_DPTOParameter = v_IMG_2_DPTO != null ?
                new ObjectParameter("V_IMG_2_DPTO", v_IMG_2_DPTO) :
                new ObjectParameter("V_IMG_2_DPTO", typeof(byte[]));
    
            var v_IMG_3_DPTOParameter = v_IMG_3_DPTO != null ?
                new ObjectParameter("V_IMG_3_DPTO", v_IMG_3_DPTO) :
                new ObjectParameter("V_IMG_3_DPTO", typeof(byte[]));
    
            var v_IMG_4_DPTOParameter = v_IMG_4_DPTO != null ?
                new ObjectParameter("V_IMG_4_DPTO", v_IMG_4_DPTO) :
                new ObjectParameter("V_IMG_4_DPTO", typeof(byte[]));
    
            var v_IMG_5_DPTOParameter = v_IMG_5_DPTO != null ?
                new ObjectParameter("V_IMG_5_DPTO", v_IMG_5_DPTO) :
                new ObjectParameter("V_IMG_5_DPTO", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARDEPARTAMENTO", v_ID_DPTOParameter, v_DIR_DPTOParameter, v_NUM_DPTOParameter, v_N_AMB_DPTOParameter, v_DESC_DPTOParameter, v_COSTO_ARRI_DPTOParameter, v_IMG_1_DPTOParameter, v_IMG_2_DPTOParameter, v_IMG_3_DPTOParameter, v_IMG_4_DPTOParameter, v_IMG_5_DPTOParameter);
        }
    
        public virtual int SP_MODIFICARDISPONIBILIDAD(Nullable<System.DateTime> v_FEC_DISP, string v_ESTA_DISP)
        {
            var v_FEC_DISPParameter = v_FEC_DISP.HasValue ?
                new ObjectParameter("V_FEC_DISP", v_FEC_DISP) :
                new ObjectParameter("V_FEC_DISP", typeof(System.DateTime));
    
            var v_ESTA_DISPParameter = v_ESTA_DISP != null ?
                new ObjectParameter("V_ESTA_DISP", v_ESTA_DISP) :
                new ObjectParameter("V_ESTA_DISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARDISPONIBILIDAD", v_FEC_DISPParameter, v_ESTA_DISPParameter);
        }
    
        public virtual int SP_MODIFICARGASTOS(Nullable<decimal> v_ID_DPTO, Nullable<decimal> v_GAST_MES, Nullable<decimal> v_GAST_AGNO)
        {
            var v_ID_DPTOParameter = v_ID_DPTO.HasValue ?
                new ObjectParameter("V_ID_DPTO", v_ID_DPTO) :
                new ObjectParameter("V_ID_DPTO", typeof(decimal));
    
            var v_GAST_MESParameter = v_GAST_MES.HasValue ?
                new ObjectParameter("V_GAST_MES", v_GAST_MES) :
                new ObjectParameter("V_GAST_MES", typeof(decimal));
    
            var v_GAST_AGNOParameter = v_GAST_AGNO.HasValue ?
                new ObjectParameter("V_GAST_AGNO", v_GAST_AGNO) :
                new ObjectParameter("V_GAST_AGNO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARGASTOS", v_ID_DPTOParameter, v_GAST_MESParameter, v_GAST_AGNOParameter);
        }
    
        public virtual int SP_MODIFICARMANTENCION(Nullable<decimal> v_ID_RMANT, Nullable<decimal> v_COST_MANT, string v_DETA_MANT)
        {
            var v_ID_RMANTParameter = v_ID_RMANT.HasValue ?
                new ObjectParameter("V_ID_RMANT", v_ID_RMANT) :
                new ObjectParameter("V_ID_RMANT", typeof(decimal));
    
            var v_COST_MANTParameter = v_COST_MANT.HasValue ?
                new ObjectParameter("V_COST_MANT", v_COST_MANT) :
                new ObjectParameter("V_COST_MANT", typeof(decimal));
    
            var v_DETA_MANTParameter = v_DETA_MANT != null ?
                new ObjectParameter("V_DETA_MANT", v_DETA_MANT) :
                new ObjectParameter("V_DETA_MANT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARMANTENCION", v_ID_RMANTParameter, v_COST_MANTParameter, v_DETA_MANTParameter);
        }
    
        public virtual int SP_MODIFICARMARCA(Nullable<decimal> v_ID_MARCA, string v_NOMBRE_MARCA)
        {
            var v_ID_MARCAParameter = v_ID_MARCA.HasValue ?
                new ObjectParameter("V_ID_MARCA", v_ID_MARCA) :
                new ObjectParameter("V_ID_MARCA", typeof(decimal));
    
            var v_NOMBRE_MARCAParameter = v_NOMBRE_MARCA != null ?
                new ObjectParameter("V_NOMBRE_MARCA", v_NOMBRE_MARCA) :
                new ObjectParameter("V_NOMBRE_MARCA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARMARCA", v_ID_MARCAParameter, v_NOMBRE_MARCAParameter);
        }
    
        public virtual int SP_MODIFICARMODELO(Nullable<decimal> v_ID_MODELO, string v_NOMBRE_MODELO)
        {
            var v_ID_MODELOParameter = v_ID_MODELO.HasValue ?
                new ObjectParameter("V_ID_MODELO", v_ID_MODELO) :
                new ObjectParameter("V_ID_MODELO", typeof(decimal));
    
            var v_NOMBRE_MODELOParameter = v_NOMBRE_MODELO != null ?
                new ObjectParameter("V_NOMBRE_MODELO", v_NOMBRE_MODELO) :
                new ObjectParameter("V_NOMBRE_MODELO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARMODELO", v_ID_MODELOParameter, v_NOMBRE_MODELOParameter);
        }
    
        public virtual int SP_MODIFICARREGION(Nullable<decimal> v_ID_RGN, string v_NOM_RGN)
        {
            var v_ID_RGNParameter = v_ID_RGN.HasValue ?
                new ObjectParameter("V_ID_RGN", v_ID_RGN) :
                new ObjectParameter("V_ID_RGN", typeof(decimal));
    
            var v_NOM_RGNParameter = v_NOM_RGN != null ?
                new ObjectParameter("V_NOM_RGN", v_NOM_RGN) :
                new ObjectParameter("V_NOM_RGN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARREGION", v_ID_RGNParameter, v_NOM_RGNParameter);
        }
    
        public virtual int SP_MODIFICARRESERVA(Nullable<decimal> v_ID_RVA, Nullable<decimal> v_NUM_PERS, string v_ESTADO_RVA)
        {
            var v_ID_RVAParameter = v_ID_RVA.HasValue ?
                new ObjectParameter("V_ID_RVA", v_ID_RVA) :
                new ObjectParameter("V_ID_RVA", typeof(decimal));
    
            var v_NUM_PERSParameter = v_NUM_PERS.HasValue ?
                new ObjectParameter("V_NUM_PERS", v_NUM_PERS) :
                new ObjectParameter("V_NUM_PERS", typeof(decimal));
    
            var v_ESTADO_RVAParameter = v_ESTADO_RVA != null ?
                new ObjectParameter("V_ESTADO_RVA", v_ESTADO_RVA) :
                new ObjectParameter("V_ESTADO_RVA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARRESERVA", v_ID_RVAParameter, v_NUM_PERSParameter, v_ESTADO_RVAParameter);
        }
    
        public virtual int SP_MODIFICARRESMANT(Nullable<decimal> v_ID_RMANT, Nullable<System.DateTime> v_FEC_RMANT)
        {
            var v_ID_RMANTParameter = v_ID_RMANT.HasValue ?
                new ObjectParameter("V_ID_RMANT", v_ID_RMANT) :
                new ObjectParameter("V_ID_RMANT", typeof(decimal));
    
            var v_FEC_RMANTParameter = v_FEC_RMANT.HasValue ?
                new ObjectParameter("V_FEC_RMANT", v_FEC_RMANT) :
                new ObjectParameter("V_FEC_RMANT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARRESMANT", v_ID_RMANTParameter, v_FEC_RMANTParameter);
        }
    
        public virtual int SP_MODIFICARSERVEXTRAS(Nullable<decimal> v_ID_SERV, string v_NOM_SERV, string v_DESC_SERV)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            var v_NOM_SERVParameter = v_NOM_SERV != null ?
                new ObjectParameter("V_NOM_SERV", v_NOM_SERV) :
                new ObjectParameter("V_NOM_SERV", typeof(string));
    
            var v_DESC_SERVParameter = v_DESC_SERV != null ?
                new ObjectParameter("V_DESC_SERV", v_DESC_SERV) :
                new ObjectParameter("V_DESC_SERV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARSERVEXTRAS", v_ID_SERVParameter, v_NOM_SERVParameter, v_DESC_SERVParameter);
        }
    
        public virtual int SP_MODIFICARTOUR(Nullable<decimal> v_ID_SERV, Nullable<decimal> v_DUR_HRA, Nullable<decimal> v_DUR_MIN, Nullable<decimal> v_COST_ADULT, Nullable<decimal> v_COST_NIGNO, Nullable<decimal> v_COST_3RA, string v_UBI_PARTIDA, string v_UBI_FIN, string v_ALIMENTACION, string v_TRANSPORTE)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            var v_DUR_HRAParameter = v_DUR_HRA.HasValue ?
                new ObjectParameter("V_DUR_HRA", v_DUR_HRA) :
                new ObjectParameter("V_DUR_HRA", typeof(decimal));
    
            var v_DUR_MINParameter = v_DUR_MIN.HasValue ?
                new ObjectParameter("V_DUR_MIN", v_DUR_MIN) :
                new ObjectParameter("V_DUR_MIN", typeof(decimal));
    
            var v_COST_ADULTParameter = v_COST_ADULT.HasValue ?
                new ObjectParameter("V_COST_ADULT", v_COST_ADULT) :
                new ObjectParameter("V_COST_ADULT", typeof(decimal));
    
            var v_COST_NIGNOParameter = v_COST_NIGNO.HasValue ?
                new ObjectParameter("V_COST_NIGNO", v_COST_NIGNO) :
                new ObjectParameter("V_COST_NIGNO", typeof(decimal));
    
            var v_COST_3RAParameter = v_COST_3RA.HasValue ?
                new ObjectParameter("V_COST_3RA", v_COST_3RA) :
                new ObjectParameter("V_COST_3RA", typeof(decimal));
    
            var v_UBI_PARTIDAParameter = v_UBI_PARTIDA != null ?
                new ObjectParameter("V_UBI_PARTIDA", v_UBI_PARTIDA) :
                new ObjectParameter("V_UBI_PARTIDA", typeof(string));
    
            var v_UBI_FINParameter = v_UBI_FIN != null ?
                new ObjectParameter("V_UBI_FIN", v_UBI_FIN) :
                new ObjectParameter("V_UBI_FIN", typeof(string));
    
            var v_ALIMENTACIONParameter = v_ALIMENTACION != null ?
                new ObjectParameter("V_ALIMENTACION", v_ALIMENTACION) :
                new ObjectParameter("V_ALIMENTACION", typeof(string));
    
            var v_TRANSPORTEParameter = v_TRANSPORTE != null ?
                new ObjectParameter("V_TRANSPORTE", v_TRANSPORTE) :
                new ObjectParameter("V_TRANSPORTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARTOUR", v_ID_SERVParameter, v_DUR_HRAParameter, v_DUR_MINParameter, v_COST_ADULTParameter, v_COST_NIGNOParameter, v_COST_3RAParameter, v_UBI_PARTIDAParameter, v_UBI_FINParameter, v_ALIMENTACIONParameter, v_TRANSPORTEParameter);
        }
    
        public virtual int SP_MODIFICARTRANSPORTE(Nullable<decimal> v_ID_SERV, Nullable<decimal> v_COST_KM_DIA, Nullable<decimal> v_COST_KM_NOC)
        {
            var v_ID_SERVParameter = v_ID_SERV.HasValue ?
                new ObjectParameter("V_ID_SERV", v_ID_SERV) :
                new ObjectParameter("V_ID_SERV", typeof(decimal));
    
            var v_COST_KM_DIAParameter = v_COST_KM_DIA.HasValue ?
                new ObjectParameter("V_COST_KM_DIA", v_COST_KM_DIA) :
                new ObjectParameter("V_COST_KM_DIA", typeof(decimal));
    
            var v_COST_KM_NOCParameter = v_COST_KM_NOC.HasValue ?
                new ObjectParameter("V_COST_KM_NOC", v_COST_KM_NOC) :
                new ObjectParameter("V_COST_KM_NOC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARTRANSPORTE", v_ID_SERVParameter, v_COST_KM_DIAParameter, v_COST_KM_NOCParameter);
        }
    
        public virtual int SP_MODIFICARUSR(Nullable<decimal> v_ID_USR, string v_EMAIL_USR, string v_CONTR_USR, string v_NOM_USR, string v_APPAT_USR, string v_APMAT_USR, Nullable<decimal> v_TEL_USR, Nullable<decimal> v_RUT_USR, string v_DV_USR, Nullable<decimal> v_CANT_RES, string v_EST_CTA, string v_TIPO_CLI)
        {
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            var v_EMAIL_USRParameter = v_EMAIL_USR != null ?
                new ObjectParameter("V_EMAIL_USR", v_EMAIL_USR) :
                new ObjectParameter("V_EMAIL_USR", typeof(string));
    
            var v_CONTR_USRParameter = v_CONTR_USR != null ?
                new ObjectParameter("V_CONTR_USR", v_CONTR_USR) :
                new ObjectParameter("V_CONTR_USR", typeof(string));
    
            var v_NOM_USRParameter = v_NOM_USR != null ?
                new ObjectParameter("V_NOM_USR", v_NOM_USR) :
                new ObjectParameter("V_NOM_USR", typeof(string));
    
            var v_APPAT_USRParameter = v_APPAT_USR != null ?
                new ObjectParameter("V_APPAT_USR", v_APPAT_USR) :
                new ObjectParameter("V_APPAT_USR", typeof(string));
    
            var v_APMAT_USRParameter = v_APMAT_USR != null ?
                new ObjectParameter("V_APMAT_USR", v_APMAT_USR) :
                new ObjectParameter("V_APMAT_USR", typeof(string));
    
            var v_TEL_USRParameter = v_TEL_USR.HasValue ?
                new ObjectParameter("V_TEL_USR", v_TEL_USR) :
                new ObjectParameter("V_TEL_USR", typeof(decimal));
    
            var v_RUT_USRParameter = v_RUT_USR.HasValue ?
                new ObjectParameter("V_RUT_USR", v_RUT_USR) :
                new ObjectParameter("V_RUT_USR", typeof(decimal));
    
            var v_DV_USRParameter = v_DV_USR != null ?
                new ObjectParameter("V_DV_USR", v_DV_USR) :
                new ObjectParameter("V_DV_USR", typeof(string));
    
            var v_CANT_RESParameter = v_CANT_RES.HasValue ?
                new ObjectParameter("V_CANT_RES", v_CANT_RES) :
                new ObjectParameter("V_CANT_RES", typeof(decimal));
    
            var v_EST_CTAParameter = v_EST_CTA != null ?
                new ObjectParameter("V_EST_CTA", v_EST_CTA) :
                new ObjectParameter("V_EST_CTA", typeof(string));
    
            var v_TIPO_CLIParameter = v_TIPO_CLI != null ?
                new ObjectParameter("V_TIPO_CLI", v_TIPO_CLI) :
                new ObjectParameter("V_TIPO_CLI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARUSR", v_ID_USRParameter, v_EMAIL_USRParameter, v_CONTR_USRParameter, v_NOM_USRParameter, v_APPAT_USRParameter, v_APMAT_USRParameter, v_TEL_USRParameter, v_RUT_USRParameter, v_DV_USRParameter, v_CANT_RESParameter, v_EST_CTAParameter, v_TIPO_CLIParameter);
        }
    
        public virtual int SP_MODIFICARVEHICULO(string v_PATENTE, string v_COLOR, Nullable<System.DateTime> v_AGNO, Nullable<decimal> v_CANT_PUERTAS, Nullable<decimal> v_CAP_PASAJ, Nullable<decimal> v_CAP_MALE, string v_ASIENTO_NIGNO, string v_PER_SILLA)
        {
            var v_PATENTEParameter = v_PATENTE != null ?
                new ObjectParameter("V_PATENTE", v_PATENTE) :
                new ObjectParameter("V_PATENTE", typeof(string));
    
            var v_COLORParameter = v_COLOR != null ?
                new ObjectParameter("V_COLOR", v_COLOR) :
                new ObjectParameter("V_COLOR", typeof(string));
    
            var v_AGNOParameter = v_AGNO.HasValue ?
                new ObjectParameter("V_AGNO", v_AGNO) :
                new ObjectParameter("V_AGNO", typeof(System.DateTime));
    
            var v_CANT_PUERTASParameter = v_CANT_PUERTAS.HasValue ?
                new ObjectParameter("V_CANT_PUERTAS", v_CANT_PUERTAS) :
                new ObjectParameter("V_CANT_PUERTAS", typeof(decimal));
    
            var v_CAP_PASAJParameter = v_CAP_PASAJ.HasValue ?
                new ObjectParameter("V_CAP_PASAJ", v_CAP_PASAJ) :
                new ObjectParameter("V_CAP_PASAJ", typeof(decimal));
    
            var v_CAP_MALEParameter = v_CAP_MALE.HasValue ?
                new ObjectParameter("V_CAP_MALE", v_CAP_MALE) :
                new ObjectParameter("V_CAP_MALE", typeof(decimal));
    
            var v_ASIENTO_NIGNOParameter = v_ASIENTO_NIGNO != null ?
                new ObjectParameter("V_ASIENTO_NIGNO", v_ASIENTO_NIGNO) :
                new ObjectParameter("V_ASIENTO_NIGNO", typeof(string));
    
            var v_PER_SILLAParameter = v_PER_SILLA != null ?
                new ObjectParameter("V_PER_SILLA", v_PER_SILLA) :
                new ObjectParameter("V_PER_SILLA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MODIFICARVEHICULO", v_PATENTEParameter, v_COLORParameter, v_AGNOParameter, v_CANT_PUERTASParameter, v_CAP_PASAJParameter, v_CAP_MALEParameter, v_ASIENTO_NIGNOParameter, v_PER_SILLAParameter);
        }
    
        public virtual int SP_SUSPENDERUSR(Nullable<decimal> v_ID_USR)
        {
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SUSPENDERUSR", v_ID_USRParameter);
        }
    
        public virtual int SP_VALIDARUSR(Nullable<decimal> v_ID_USR)
        {
            var v_ID_USRParameter = v_ID_USR.HasValue ?
                new ObjectParameter("V_ID_USR", v_ID_USR) :
                new ObjectParameter("V_ID_USR", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_VALIDARUSR", v_ID_USRParameter);
        }
    }
}
