//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.CHECKIN = new HashSet<CHECKIN>();
            this.CHECKOUT = new HashSet<CHECKOUT>();
            this.RES_MANT = new HashSet<RES_MANT>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int ID_USR { get; set; }
        public string EMAIL_USR { get; set; }
        public string CONTR_USR { get; set; }
        public string NOM_USR { get; set; }
        public string APPAT_USR { get; set; }
        public string APMAT_USR { get; set; }
        public int TEL_USR { get; set; }
        public int RUT_USR { get; set; }
        public string DV_USR { get; set; }
        public Nullable<short> CANT_RES { get; set; }
        public string EST_CTA { get; set; }
        public string TIPO_CLI { get; set; }
        public short ID_TIPO_USR { get; set; }
    
        public virtual ICollection<CHECKIN> CHECKIN { get; set; }
        public virtual ICollection<CHECKOUT> CHECKOUT { get; set; }
        public virtual ICollection<RES_MANT> RES_MANT { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
