//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoReal.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public VEHICULO()
        {
            this.CONDUCTOR = new HashSet<CONDUCTOR>();
        }
    
        public string PATENTE { get; set; }
        public string COLOR { get; set; }
        public System.DateTime AGNO { get; set; }
        public short CANT_PUERTAS { get; set; }
        public short CAP_PASAJ { get; set; }
        public short CAP_MALE { get; set; }
        public string ASIENTO_NIGNO { get; set; }
        public string PER_SILLA { get; set; }
        public short ID_MODELO { get; set; }
    
        public virtual ICollection<CONDUCTOR> CONDUCTOR { get; set; }
        public virtual MODELO MODELO { get; set; }
    }
}
