# Generated by Django 3.2.8 on 2021-10-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaExterna',
            fields=[
                ('id_agencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_age', models.CharField(max_length=100)),
                ('email_age', models.CharField(max_length=100, unique=True)),
                ('tel_age', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'agencia_externa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_arti', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_arti', models.CharField(max_length=100)),
                ('cant_arti', models.IntegerField(blank=True, null=True)),
                ('deta_arti', models.CharField(max_length=2000)),
                ('valor_arti', models.IntegerField()),
            ],
            options={
                'db_table': 'articulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_com', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_com', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id_cnd', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_cnd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'condominio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('rut_conduc', models.IntegerField(primary_key=True, serialize=False)),
                ('dv_conduc', models.CharField(max_length=1)),
                ('nom_conduc', models.CharField(max_length=50)),
                ('appat_conduc', models.CharField(max_length=50)),
                ('apmat_conduc', models.CharField(max_length=50)),
                ('email_conduc', models.CharField(max_length=100, unique=True)),
                ('tel_conduc', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContServ',
            fields=[
                ('id_cont_serv', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_cont', models.DateField()),
                ('costo_total', models.IntegerField()),
                ('deta_cont', models.CharField(max_length=2000)),
                ('fec_acord', models.DateField()),
                ('hora_acord', models.CharField(max_length=5)),
                ('lugar_recogida', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_destino', models.CharField(blank=True, max_length=100, null=True)),
                ('km_rec', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('est_cont', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'cont_serv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dpto', models.IntegerField(primary_key=True, serialize=False)),
                ('dir_dpto', models.CharField(max_length=100)),
                ('num_dpto', models.IntegerField()),
                ('n_amb_dpto', models.BooleanField()),
                ('desc_dpto', models.CharField(max_length=2000)),
                ('costo_arri_dpto', models.IntegerField()),
                ('img_1_dpto', models.BinaryField()),
                ('img_2_dpto', models.BinaryField(blank=True, null=True)),
                ('img_3_dpto', models.BinaryField(blank=True, null=True)),
                ('img_4_dpto', models.BinaryField(blank=True, null=True)),
                ('img_5_dpto', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('fec_disp', models.DateField(primary_key=True, serialize=False)),
                ('esta_disp', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'disponibilidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id_gastos', models.IntegerField(primary_key=True, serialize=False)),
                ('gast_mes', models.IntegerField()),
                ('gast_agno', models.IntegerField()),
            ],
            options={
                'db_table': 'gastos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mant', models.IntegerField(primary_key=True, serialize=False)),
                ('cost_mant', models.IntegerField()),
                ('deta_mant', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'mantencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'modelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_rgn', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_rgn', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_rva', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_ini_rva', models.DateField()),
                ('fec_fin_rva', models.DateField()),
                ('num_pers', models.IntegerField()),
                ('estado_rva', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResMant',
            fields=[
                ('id_rmant', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_rmant', models.DateField()),
            ],
            options={
                'db_table': 'res_mant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servextras',
            fields=[
                ('id_serv', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_serv', models.CharField(max_length=100)),
                ('tipo_serv', models.CharField(max_length=1)),
                ('desc_serv', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'servextras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usr', models.BooleanField(primary_key=True, serialize=False)),
                ('tipo_usr', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usr', models.IntegerField(primary_key=True, serialize=False)),
                ('email_usr', models.CharField(max_length=100, unique=True)),
                ('contr_usr', models.CharField(max_length=50)),
                ('nom_usr', models.CharField(max_length=50)),
                ('appat_usr', models.CharField(max_length=50)),
                ('apmat_usr', models.CharField(max_length=50)),
                ('tel_usr', models.IntegerField(unique=True)),
                ('rut_usr', models.IntegerField(unique=True)),
                ('dv_usr', models.CharField(max_length=1)),
                ('cant_res', models.IntegerField(blank=True, null=True)),
                ('est_cta', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_cli', models.CharField(blank=True, max_length=25, null=True)),
                ('id_tipo_usr', models.BooleanField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=30)),
                ('agno', models.DateField()),
                ('cant_puertas', models.BooleanField()),
                ('cap_pasaj', models.IntegerField()),
                ('cap_male', models.IntegerField()),
                ('asiento_nigno', models.CharField(max_length=2)),
                ('per_silla', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id_rva', models.OneToOneField(db_column='id_rva', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.reserva')),
                ('deta_chi', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'checkin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id_rva', models.OneToOneField(db_column='id_rva', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.reserva')),
                ('cost_multa', models.IntegerField()),
                ('deta_cho', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'checkout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_rva', models.OneToOneField(db_column='id_rva', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.reserva')),
                ('monto_total', models.IntegerField()),
                ('monto_arr', models.IntegerField()),
                ('abono_req', models.IntegerField()),
                ('monto_serv_extra', models.IntegerField()),
                ('monto_multas', models.IntegerField()),
                ('monto_pagado', models.IntegerField()),
                ('est_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_serv', models.OneToOneField(db_column='id_serv', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.servextras')),
                ('dur_hra', models.IntegerField()),
                ('dur_min', models.IntegerField()),
                ('cost_adult', models.IntegerField()),
                ('cost_nigno', models.IntegerField()),
                ('cost_3ra', models.IntegerField()),
                ('ubi_partida', models.CharField(max_length=100)),
                ('ubi_fin', models.CharField(max_length=100)),
                ('alimentacion', models.CharField(max_length=2)),
                ('transporte', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_serv', models.OneToOneField(db_column='id_serv', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.servextras')),
                ('cost_km_dia', models.IntegerField()),
                ('cost_km_noc', models.IntegerField()),
                ('extra_fest', models.IntegerField()),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
    ]
